// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://psczvkseaxdlhdaebwcy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBzY3p2a3NlYXhkbGhkYWVid2N5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDczMTY1NDcsImV4cCI6MjA2Mjg5MjU0N30.qVB_Cl33opEMs7DMdfoVZULNJ1VEksksIf7-kcYDBxU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);